package org.java.VaadinMeetingBook.samples.BookMeeting;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NewtonFormDesign extends CssLayout {
    protected TextField date;
    protected TextField meetingRoom;
    protected TextField meetingVenue;
    protected TextField meetingStartTime;
    protected TextField meetingEndTime;
    protected TextField meetingPurpose;
    protected TextField userName;
    protected Button  Modify;
    protected Button  discard;
    protected Button  cancel;
    protected Button  delete;
    


    public NewtonFormDesign() {
        Design.read(this);
    }
}